// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mathletics.Context;

namespace mathletics.Migrations
{
    [DbContext(typeof(MathleticsContext))]
    [Migration("20190717161432_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("mathletics.Context.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Choice");

                    b.Property<int?>("PlayerId");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("mathletics.Context.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Score");

                    b.Property<string>("SessionId");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("mathletics.Context.ProblemList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("ProblemList");
                });

            modelBuilder.Entity("mathletics.Context.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CorrectAnswer");

                    b.Property<string>("Option1");

                    b.Property<string>("Option2");

                    b.Property<string>("Option3");

                    b.Property<int?>("ProblemListId");

                    b.Property<string>("Prompt");

                    b.HasKey("Id");

                    b.HasIndex("ProblemListId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("mathletics.Context.Answer", b =>
                {
                    b.HasOne("mathletics.Context.Player")
                        .WithMany("Answer")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("mathletics.Context.Question", b =>
                {
                    b.HasOne("mathletics.Context.ProblemList")
                        .WithMany("Questions")
                        .HasForeignKey("ProblemListId");
                });
#pragma warning restore 612, 618
        }
    }
}
